import heroFallback from '../assets/hero.jpg';
// Hero slider data. Slides are managed from the Admin Dashboard's
// "Hero Slider" tab and stored in the `hero_slides` table + `images` bucket.
//
// Expected schema (run once in the Supabase SQL editor):
//
//   create table if not exists hero_slides (
//     id bigint generated by default as identity primary key,
//     image_path text not null,
//     sort_order int not null default 0,
//     created_at timestamptz not null default now()
//   );
//   alter table hero_slides enable row level security;
//   create policy "Public read hero slides" on hero_slides
//     for select using (true);
//   create policy "Authenticated manage hero slides" on hero_slides
//     for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
//
import { supabase } from './supabaseClient';

export const HERO_FALLBACK_IMAGE = heroFallback;

function resolveHeroImage(path) {
  if (!path) return null;
  if (path.startsWith('http')) return path;
  const { data } = supabase.storage.from('images').getPublicUrl(path);
  return data.publicUrl;
}

/** Fetch admin-uploaded hero slides. Falls back to one static image if none exist. */
export async function fetchHeroSlides() {
  const { data, error } = await supabase
    .from('hero_slides')
    .select('id, image_path, sort_order')
    .order('sort_order', { ascending: true });

  if (error || !data || data.length === 0) {
    return [{ id: 'fallback', image: HERO_FALLBACK_IMAGE }];
  }

  const slides = data
    .map((row) => ({ id: row.id, image: resolveHeroImage(row.image_path) }))
    .filter((s) => s.image);

  return slides.length > 0 ? slides : [{ id: 'fallback', image: HERO_FALLBACK_IMAGE }];
}
